* LoRA
[[https://www.youtube.com/watch?v=cUhAyyzlv2o&list=PLmL13yqb6OxdeOi97EvI8QeO8o-PqeQ0g][LoRa playlist]]
LoRa is an acronym of *Lo*ng *Ra*nge and it's a wireless technology where
a low power sender trasmit small data packages ( 0.3 kbps to 5.5 kbps)
to a receiver over a long distance.
*Gateways* can handle hundreds of device at the same time:

** Key words 
1) Radio and modulation = LoRa
2) Wireless technology
3) *Long distance*
4) Small data packages such as sensor data
5) *Low power consuption* ( around 20 mW)
6) SEMTECH : LoRa is a trademark of Semetech corporation 
** LPWAN : low power wide area network
Wireless communication designed for sending small data packages over long
distances.The devices operates on a battery.

There are a number of competing technologies in the LPWAN such as : LoRa,
Narrowband iot (NB-IoT),Sigfox...

LoRa can't send audio or video data instead sends small data such as sensor
data ( temperature,humity..)
** LoRa end nodes
A LoRa end node consists of 2 parts : 
- Radio module with antenna
- Microprocessor to process for example the sensor data

LoRa end nodes are often battery powered.

LoRa end nodes have a wireless trasceiver,if the device
also has a sensor, the device also acts as a remote device
such devices is called as *mote*,short of remote.
** LoRa Gateway
LoRa Gateway consists of 2 parts :
- A radio module with antenna.
- A microprocessor to process the data
LoRa Gateways are mains powered and connected to the internet
Multiple gateways can receive data from the same end node.
Gateways can listen to multiple frequencies simultaneously,
in every spreading factor at each frecuency.
** LoRa Network
LoRaWAN network architecture is deployed in a start topology.
The communication between the end node and gateway is bidirectional
which means the end node can send data to the gateway but it can also
receive data from the gateway.
Communication from the end node to the gateway is called *uplink*.
Communication from the gateway to the end node is called *downlink*.

End Nodes --> Gateways --> Network Server --> Server Apps

An end node can send data to multiple gateways.Gateways forward
the packages to the network server.The network server filters
the packages and forward the best ones to the correct application server.
Also the network server determinates with of the gateways is the perfect
one to send the data back.

LoRaWAN doesn't support end communication between nodes.But it's possible
using a library for that.

** LoRa Alliance

A non-profit organisation of more than 500 companies to promote LPWAN through
the development and promotion of LoRaWAN.

** ISM Band

LoRa operates in the unlicensed ISM (Industrial,Scientific and Medical) radio band 
that are available wordwide.
In Europe the band goes from 863-870 MHz.
Because anyone can use these band there are some rules set otherwise the band
became unusable ( lots of signal interferances ).In Europe The ETSI ( Europe
Telecommunication Standar Institute) manages the radio spectrum to ensure 
co-existance between all the different radio technologies.
In Europe the ISM radio band must comply to the following rules : 
- For uplink, the maximun transmission power is 25mW (14 dBm).For downlink,
the maximun transmission power is 0.5W(27dBm)
- Maximun allowed antenna gain + 2.15 dBi.

Besides, the ISM rules the network operator can also add additional rules.
One of the most commond network operator is *The Things Network*

** Time on Air
Time on Air is the amount of time the signal takes from the sender to the
receiver.

** Duty cycle

The duty cycle is the proportion of time during which a component is operated.
In Europe the duty cycle goes from 0.1% to 1% per day, depending of the channel.

For example and end node with a TOR = 530ms and Duty cycle equal a 1%, before
transmit again the signal it must waits 0.99*530 ms

** LoRaWAN Classes
- A(ll) : battery powered devices.Each device uplink to the gateway and is followed
by two short downlink receive windows.
- B(eacon) : same as class A but these device also opens extra receive windows at
scheduled times 
- C(ontinuous) : same as class A but the devices are continously listening.Hence these
devices uses more power and are often mains powered.
*** Class A
Before the next transmission, at t1 and t2 second after an uplink trasmission an end
node opens two receive slots.The gateway can respond within the first receive slot 
or the second receive slot, but not both.
*** Class B
Similar to class A, but class B devices opens extra receive slots at  scheduled times.
The gateway sends beacon to end devices to synchronised allowing gateway to know when
the node is listening.
*** Class C
Similar to class B, but it continous listening gateway responses before an uplink
transmission.

** TODO Lora Playlist

[[https://www.youtube.com/watch?v=6WMzRrmMjQU&list=PLmL13yqb6OxdeOi97EvI8QeO8o-PqeQ0g&index=2][end this video minute 5:30]] 
